spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/my_review
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password:
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
